window.AppStoreApp={id:'appstore',name:'Nova Shop',description:'Discover apps made for Nova OS.',icon:'assets/icons/neon/shop.png',width:900,height:650,mount(body){
 const apps=[window.LiveWallpaperApp,ClockApp,TimerApp,MeetApp,ChatApp,CalendarApp,TerminalApp,GalleryApp,CursorStudioApp,BeatLabApp,NovaAIApp,GoogleClassroomApp,NovaCloudGamingApp,window.TikTokApp].filter(Boolean);
 body.innerHTML=`<div class="store-app"><header class="store-v3-head"><div class="store-v3-top"><div class="store-v3-brand"><div class="store-v3-logo">✦</div><div><h1>Nova Shop</h1><p>Apps, tools, and experiences for your Nova desktop.</p></div></div><label class="store-search"><span>⌕</span><input id="store-search" type="search" placeholder="Search the Nova Shop..."></label></div><nav class="store-nav" id="store-nav"><button class="active" data-cat="all">All</button><button data-cat="featured">Featured</button><button data-cat="productivity">Productivity</button><button data-cat="social">Social</button><button data-cat="creative">Creative</button><button data-cat="entertainment">Entertainment</button><button data-cat="utilities">Utilities</button></nav></header><div class="store-v3-body"><section class="store-feature"><div><span class="eyebrow">WELCOME TO THE SHOP</span><h2>Make Nova yours.</h2><p>Find useful apps, fun tools, and new experiences. Install an app and it will appear on your desktop and Start menu.</p></div><div class="store-feature-badge">✦</div></section><div class="store-v3-section"><div><span class="eyebrow">DISCOVER</span><h3 id="store-title">All apps</h3></div><small id="store-count"></small></div><div id="store-grid" class="store-v3-grid"></div></div></div>`;
 const grid=body.querySelector('#store-grid'),search=body.querySelector('#store-search');let category='all';
 const categoryFor=id=>({'live-wallpaper':'creative',clock:'utilities',timer:'utilities',meet:'social',chat:'social',calendar:'productivity',terminal:'productivity',gallery:'creative',cursor:'creative',beatlab:'creative','nova-ai':'featured','google-classroom':'productivity','nova-cloud-gaming':'entertainment',tiktok:'social'})[id]||'productivity';
 const labelFor=id=>({'live-wallpaper':'Creative',clock:'Utilities',timer:'Utilities',meet:'Social',chat:'Social',calendar:'Productivity',terminal:'Productivity',gallery:'Creative',cursor:'Creative',beatlab:'Creative','nova-ai':'Featured','google-classroom':'Education','nova-cloud-gaming':'Entertainment',tiktok:'Social'})[id]||'App';
 function render(){const q=(search.value||'').trim().toLowerCase();const filtered=apps.filter(a=>(category==='all'||categoryFor(a.id)===category)&&(!q||a.name.toLowerCase().includes(q)||a.description.toLowerCase().includes(q)));body.querySelector('#store-title').textContent=category==='all'?'All apps':category[0].toUpperCase()+category.slice(1);body.querySelector('#store-count').textContent=filtered.length+' app'+(filtered.length===1?'':'s');grid.innerHTML=filtered.length?filtered.map(a=>{const installed=OS.isInstalled(a.id);return `<article class="store-v3-card"><div class="store-v3-card-top"><div class="store-v3-icon"><img src="${a.icon}" alt=""></div><div><h4>${a.name}</h4><p class="desc">${a.description}</p><span class="store-v3-tag">${labelFor(a.id)}</span></div></div><div class="store-v3-bottom"><small>${installed?(a.id==='google-classroom'?'Preinstalled in Nova OS':'Already on your desktop'):'Ready to install'}</small><button class="app-button ${installed?'installed':''}" data-id="${a.id}" ${installed?'disabled':''}>${installed?'Installed':'Install'}</button></div></article>`}).join(''):'<div class="store-empty">No apps match your search.</div>';
 grid.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{OS.install(b.dataset.id);render()});}
 body.querySelectorAll('#store-nav button').forEach(b=>b.onclick=()=>{body.querySelectorAll('#store-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.cat;render()});search.oninput=render;render();return()=>{}}};
