window.BeatLabApp={id:'beatlab',name:'Nova Beat Lab',description:'Build polished loops with drums, bass, chords, melodies, presets, and custom sounds.',icon:'assets/icons/beatlab.svg',width:1040,height:720,mount(body){
  const presets={
    'Nova Pulse':{bpm:110,kick:[0,4,8,12],snare:[4,12],hat:[0,2,4,6,8,10,12,14],clap:[4,12],perc:[3,7,11,15],bass:[0,3,8,11],chord:[0,8],melody:[2,6,10,14]},
    'Neon Bounce':{bpm:124,kick:[0,3,6,8,10,14],snare:[4,12],hat:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],clap:[4,12],perc:[2,6,10,14],bass:[0,6,8,14],chord:[0,4,8,12],melody:[1,5,9,13]},
    'Night Drive':{bpm:104,kick:[0,8,10],snare:[4,12],hat:[2,6,10,14],clap:[4,12],perc:[3,11],bass:[0,4,8,12],chord:[0,8],melody:[3,7,11,15]},
    'Hyper Arcade':{bpm:138,kick:[0,2,4,8,10,12],snare:[4,12],hat:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],clap:[4,12],perc:[1,5,9,13],bass:[0,2,6,8,10,14],chord:[0,4,8,12],melody:[0,3,6,9,12,15]},
    'Chill Orbit':{bpm:88,kick:[0,8],snare:[4,12],hat:[2,6,10,14],clap:[12],perc:[7,15],bass:[0,8],chord:[0,4,8,12],melody:[3,7,11,15]},
    'Pixel Rush':{bpm:150,kick:[0,4,6,8,12,14],snare:[4,12],hat:[0,2,4,6,8,10,12,14],clap:[4,12],perc:[1,3,9,11],bass:[0,6,8,14],chord:[2,6,10,14],melody:[0,2,4,8,10,12]},
    'Future Bass':{bpm:128,kick:[0,6,8,14],snare:[4,12],hat:[2,4,6,8,10,12,14],clap:[4,12],perc:[3,11],bass:[0,6,8,14],chord:[0,4,8,12],melody:[1,5,9,13]},
    'Lo-Fi Room':{bpm:76,kick:[0,7,10],snare:[4,12],hat:[1,3,5,7,9,11,13,15],clap:[12],perc:[6,14],bass:[0,7,10],chord:[0,8],melody:[2,6,10,14]},
    'Starlight':{bpm:116,kick:[0,4,8,12],snare:[4,12],hat:[1,3,5,7,9,11,13,15],clap:[4,12],perc:[2,10],bass:[0,3,8,11],chord:[0,4,8,12],melody:[1,6,9,14]},
    'Cyber City':{bpm:132,kick:[0,3,6,8,11,14],snare:[4,12],hat:[0,2,4,6,8,10,12,14],clap:[4,12],perc:[1,7,9,15],bass:[0,3,6,8,11,14],chord:[0,8],melody:[2,5,10,13]},
    'Sunset Ride':{bpm:98,kick:[0,8,10],snare:[4,12],hat:[2,6,10,14],clap:[12],perc:[3,7,11],bass:[0,4,8,12],chord:[0,4,8,12],melody:[3,7,11,15]},
    'Boss Battle':{bpm:144,kick:[0,3,4,7,8,11,12,15],snare:[4,12],hat:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],clap:[4,12],perc:[2,6,10,14],bass:[0,3,7,8,11,15],chord:[0,8],melody:[0,4,7,10,12,15]}
  };
  const rows=[['kick','KICK'],['snare','SNARE'],['hat','HI-HAT'],['clap','CLAP'],['perc','PERC'],['bass','BASS'],['chord','CHORD'],['melody','MELODY'],['custom','CUSTOM']];
  const clone=x=>JSON.parse(JSON.stringify(x));
  let pattern=clone(presets['Nova Pulse']),preset='Nova Pulse',playing=false,step=-1,timer=null,audio=null,customBuffer=null,bpm=110,swing=0,volume=.75;
  const ensure=()=>{if(audio)return audio;audio=new(window.AudioContext||window.webkitAudioContext)();return audio};
  const noteFor=(row)=>({bass:[55,65.41,73.42,82.41],melody:[261.63,293.66,329.63,392],chord:[130.81,164.81,196,246.94]})[row]||[261.63,293.66,329.63,392];
  function hit(type,when){
    const a=ensure();if(a.state==='suspended')a.resume();
    if(type==='custom'&&customBuffer){const s=a.createBufferSource();s.buffer=customBuffer;const g=a.createGain();g.gain.value=.65*volume;s.connect(g).connect(a.destination);s.start(when);return}
    if(type==='hat'||type==='perc'){const n=a.createBufferSource(),buf=a.createBuffer(1,a.sampleRate*(type==='hat'?.075:.13),a.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2);n.buffer=buf;const f=a.createBiquadFilter();f.type='highpass';f.frequency.value=type==='hat'?5200:1800;const g=a.createGain();g.gain.setValueAtTime((type==='hat'?.17:.13)*volume,when);g.gain.exponentialRampToValueAtTime(.001,when+(type==='hat'?.07:.12));n.connect(f).connect(g).connect(a.destination);n.start(when);return}
    const o=a.createOscillator(),g=a.createGain();o.type=type==='bass'?'triangle':type==='chord'?'sine':type==='melody'?'triangle':'square';
    const idx=step%4, base=type==='kick'?105:type==='snare'?190:noteFor(type)[idx];o.frequency.value=base;if(type==='kick')o.frequency.exponentialRampToValueAtTime(45,when+.18);
    if(type==='chord')o.detune.value=(idx%3)*7;
    const gain=(type==='snare'?.12:type==='kick'?.22:type==='bass'?.13:type==='chord'?.07:.11)*volume;g.gain.setValueAtTime(gain,when);g.gain.exponentialRampToValueAtTime(.001,when+(type==='kick'?.22:type==='snare'?.11:type==='bass'?.2:type==='chord'?.35:.22));o.connect(g).connect(a.destination);o.start(when);o.stop(when+.4);
  }
  function start(){if(playing)return;playing=true;let i=0;const tick=()=>{if(!playing)return;step=i;renderSteps();const now=ensure().currentTime;Object.keys(pattern).forEach(k=>{if(pattern[k]?.includes(i))hit(k,now+.015)});i=(i+1)%16;const beat=60000/bpm/4;timer=setTimeout(tick,beat*(1+(i%2?swing/100:0)))};tick();renderTransport()}
  function stop(){playing=false;clearTimeout(timer);timer=null;step=-1;renderSteps();renderTransport()}
  function renderTransport(){const b=body.querySelector('#beat-play');if(b)b.textContent=playing?'■ Stop':'▶ Play'}
  function renderSteps(){body.querySelectorAll('.beat-step').forEach(x=>x.classList.toggle('active-step',Number(x.dataset.step)===step));body.querySelectorAll('.beat-cell').forEach(x=>x.classList.toggle('on',(pattern[x.dataset.row]||[]).includes(Number(x.dataset.step))))}
  function randomize(){rows.forEach(([id])=>{if(id==='custom')return;const density=id==='hat'?9:id==='kick'?4:5;pattern[id]=Array.from({length:16},(_,i)=>i).filter(()=>Math.random()<density/16)});renderSteps();OS.toast('Random beat generated')}
  function clear(){rows.forEach(([id])=>pattern[id]=[]);renderSteps()}
  function draw(){body.innerHTML=`<div class="beatlab-app"><header class="beatlab-head"><div><span class="media-eyebrow">NOVA LABS</span><h1>Nova Beat Lab</h1><p>Build loops, switch presets, remix patterns, and make your own sound.</p></div><div class="beatlab-actions"><select id="beat-preset">${Object.keys(presets).map(x=>`<option>${x}</option>`).join('')}</select><button id="beat-random">✦ Randomize</button><button id="beat-clear">Clear</button><button id="beat-save">Save Beat</button><button id="beat-play" class="beat-primary">▶ Play</button></div></header><div class="beatlab-toolbar"><label>BPM <input id="beat-bpm" type="range" min="60" max="180" value="110"><strong id="beat-bpm-value">110</strong></label><label>Swing <input id="beat-swing" type="range" min="0" max="35" value="0"><strong id="beat-swing-value">0%</strong></label><label>Volume <input id="beat-volume" type="range" min="0" max="1" step=".01" value=".75"></label><label class="beat-upload">Custom sound <input id="beat-file" type="file" accept="audio/*"></label><span id="beat-status">Click cells to edit. Use Randomize for a fresh pattern.</span></div><section class="beat-grid-wrap"><div class="beat-grid" id="beat-grid"></div></section><section class="saved-beats"><div><span class="media-eyebrow">YOUR CREATIONS</span><h2>Saved beats</h2></div><div id="saved-beats-list"></div></section></div>`;
    const grid=body.querySelector('#beat-grid');grid.innerHTML='<div></div>'+Array.from({length:16},(_,i)=>`<div class="beat-step" data-step="${i}">${i+1}</div>`).join('')+rows.map(([id,label])=>`<div class="beat-row-label">${label}</div>${Array.from({length:16},(_,i)=>`<button type="button" class="beat-cell" data-row="${id}" data-step="${i}" aria-label="${label} step ${i+1}"></button>`).join('')}`).join('');
    const presetEl=body.querySelector('#beat-preset');presetEl.value=preset;presetEl.onchange=e=>{preset=e.target.value;pattern=clone(presets[preset]);bpm=Number(pattern.bpm)||110;delete pattern.bpm;body.querySelector('#beat-bpm').value=bpm;body.querySelector('#beat-bpm-value').textContent=bpm;renderSteps()};
    body.querySelector('#beat-play').onclick=()=>playing?stop():start();body.querySelector('#beat-random').onclick=randomize;body.querySelector('#beat-clear').onclick=clear;
    body.querySelector('#beat-bpm').oninput=e=>{bpm=Number(e.target.value);body.querySelector('#beat-bpm-value').textContent=bpm};body.querySelector('#beat-swing').oninput=e=>{swing=Number(e.target.value);body.querySelector('#beat-swing-value').textContent=swing+'%'};body.querySelector('#beat-volume').oninput=e=>{volume=Number(e.target.value)};
    body.querySelectorAll('.beat-cell').forEach(c=>c.onclick=()=>{const r=c.dataset.row,s=Number(c.dataset.step),arr=pattern[r]||[];pattern[r]=arr.includes(s)?arr.filter(x=>x!==s):[...arr,s].sort((a,b)=>a-b);renderSteps()});
    body.querySelector('#beat-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{customBuffer=await ensure().decodeAudioData(await f.arrayBuffer());body.querySelector('#beat-status').textContent=`Custom sound loaded: ${f.name}`;body.querySelectorAll('[data-row="custom"]').forEach(x=>x.classList.add('custom-ready'))}catch{body.querySelector('#beat-status').textContent='That audio file could not be loaded.'}};
    body.querySelector('#beat-save').onclick=()=>{const saved=Store.load('beatlab-saved',[]);saved.unshift({name:`My Beat ${Date.now().toString().slice(-5)}`,bpm,swing,pattern:clone(pattern)});Store.save('beatlab-saved',saved.slice(0,30));renderSaved();OS.toast('Beat saved')};renderSteps();renderSaved();
  }
  function renderSaved(){const box=body.querySelector('#saved-beats-list');if(!box)return;const saved=Store.load('beatlab-saved',[]);box.innerHTML=saved.length?saved.map((b,i)=>`<button class="saved-beat" data-i="${i}"><strong>${escapeHtml(b.name)}</strong><small>${b.bpm} BPM · ${b.swing||0}% swing</small></button>`).join(''):'<span class="saved-empty">Save a beat and it will appear here.</span>';box.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const s=saved[Number(b.dataset.i)];pattern=clone(s.pattern||{});bpm=Number(s.bpm)||110;swing=Number(s.swing)||0;body.querySelector('#beat-bpm').value=bpm;body.querySelector('#beat-bpm-value').textContent=bpm;body.querySelector('#beat-swing').value=swing;body.querySelector('#beat-swing-value').textContent=swing+'%';renderSteps()})}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  draw();return()=>{stop();audio?.close?.().catch?.(()=>{})}
}};
