window.ChatApp={id:'chat',name:'Chat',description:'Private messaging with real accounts and friend requests.',icon:'assets/icons/neon/chat.png',width:980,height:650,mount(body){
body.innerHTML=`<div class="chat-app"><aside class="chat-sidebar"><div class="chat-brand"><span>✦</span><div><strong>Nova Chat</strong><small>Private messages</small></div></div><div class="chat-profile"><div class="contact-avatar big">${NovaUser.username[0].toUpperCase()}</div><div><strong>${NovaUser.username}</strong><small>Signed in</small></div></div><div class="chat-add"><input id="chat-add-user" placeholder="Add username"><button id="chat-add-btn">Add</button></div><div id="chat-requests"></div><div class="chat-section-label">Contacts</div><div id="chat-contacts" class="chat-contacts"></div></aside><section class="chat-main"><div class="chat-empty" id="chat-empty"><div class="chat-empty-icon">✦</div><h2>Your conversations</h2><p>Add a Nova user to start chatting.</p></div><div class="chat-conversation hidden" id="chat-conversation"><header><div class="contact-avatar" id="chat-avatar">?</div><div><strong id="chat-name">Contact</strong><small id="chat-connection">Loading…</small></div><span class="chat-live-dot" id="chat-live-dot"></span></header><div id="chat-messages" class="chat-messages"></div><form id="chat-form" class="chat-compose"><input id="chat-input" maxlength="4000" placeholder="Write a message…" autocomplete="off"><button>Send</button></form></div></section></div>`;
const contactsEl=body.querySelector('#chat-contacts'),reqEl=body.querySelector('#chat-requests'),empty=body.querySelector('#chat-empty'),conv=body.querySelector('#chat-conversation'),msgs=body.querySelector('#chat-messages'),input=body.querySelector('#chat-input');let contacts=[],active=null,events=null,poll=null,lastMessageId='';
const api=NovaAuth.api;
async function refresh(){try{const d=await api('/api/social');contacts=(Array.isArray(d.contacts)?d.contacts:[]).map(x=>typeof x==='string'?{username:x}:x);render();renderRequests(Array.isArray(d.requests)?d.requests:[]);if(active){const next=contacts.find(c=>c.username===active.username);if(next)await select(next,true)}}catch(e){OS.toast(e.message||'Unable to load Nova Chat.')}}
function render(){contactsEl.innerHTML='';contacts.forEach(c=>{const b=document.createElement('button');b.className='chat-contact '+(active?.username===c.username?'active':'');b.innerHTML=`<span class="contact-avatar">${c.username[0].toUpperCase()}</span><span><strong></strong><small>@${c.username}</small></span><i>›</i>`;b.querySelector('strong').textContent=c.username;b.onclick=()=>select(c);contactsEl.append(b)})}
function renderRequests(rs){reqEl.innerHTML='';if(!rs.length)return;const title=document.createElement('div');title.className='chat-section-label';title.textContent='Requests';reqEl.append(title);rs.forEach(r=>{const card=document.createElement('div');card.className='chat-request';card.innerHTML=`<strong></strong><small>wants to chat</small><div><button class="accept">Accept</button><button class="decline">Decline</button></div>`;card.querySelector('strong').textContent='@'+r.username;card.querySelector('.accept').onclick=async()=>{try{await api('/api/request/respond',{method:'POST',body:JSON.stringify({username:r.username,accept:true})});await refresh()}catch(e){OS.toast(e.message)}};card.querySelector('.decline').onclick=async()=>{try{await api('/api/request/respond',{method:'POST',body:JSON.stringify({username:r.username,accept:false})});await refresh()}catch(e){OS.toast(e.message)}};reqEl.append(card)})}
function addMessage(m,self){const row=document.createElement('div');row.className='chat-message '+(self?'self':'');const time=new Date(m.at||Date.now()).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});row.innerHTML='<span class="chat-bubble"></span><time></time>';row.querySelector('.chat-bubble').textContent=m.text;row.querySelector('time').textContent=time;msgs.append(row);msgs.scrollTop=msgs.scrollHeight}
async function loadMessages(silent=false){if(!active)return;try{const d=await api('/api/messages?with='+encodeURIComponent(active.username));const list=Array.isArray(d.messages)?d.messages:[];const newest=list.at(-1)?.id||'';if(newest!==lastMessageId||!silent){msgs.innerHTML='';list.forEach(m=>addMessage(m,m.from===NovaUser.username));lastMessageId=newest}body.querySelector('#chat-connection').textContent='Connected';body.querySelector('#chat-live-dot').classList.add('on')}catch{body.querySelector('#chat-connection').textContent='Server unavailable';body.querySelector('#chat-live-dot').classList.remove('on')}}
async function select(c,silent=false){active=c;empty.classList.add('hidden');conv.classList.remove('hidden');body.querySelector('#chat-name').textContent=c.username;body.querySelector('#chat-avatar').textContent=c.username[0].toUpperCase();lastMessageId='';await loadMessages(silent);render()}
function connect(){events=NovaAuth.events(m=>{if(m.type==='chat'&&active?.username===m.message.from)loadMessages();if(m.type==='request'||m.type==='accepted'){OS.toast(m.type==='request'?`@${m.from} sent a chat request`:`@${m.username} accepted your request`);refresh()}});poll=setInterval(()=>{refresh();loadMessages(true)},3500)}
body.querySelector('#chat-add-btn').onclick=async()=>{const username=body.querySelector('#chat-add-user').value.trim();if(!username)return;try{const d=await api('/api/user/check?username='+encodeURIComponent(username));if(!d.exists)throw Error('No Nova account with that username.');await api('/api/request',{method:'POST',body:JSON.stringify({username})});OS.toast('Chat request sent to @'+username);body.querySelector('#chat-add-user').value='';refresh()}catch(e){OS.toast(e.message)}};
body.querySelector('#chat-add-user').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();body.querySelector('#chat-add-btn').click()}};
body.querySelector('#chat-form').onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text||!active)return;const target=active.username;input.disabled=true;try{const d=await api('/api/chat/send',{method:'POST',body:JSON.stringify({to:target,text})});addMessage(d.message,true);lastMessageId=d.message.id;input.value=''}catch(e){OS.toast(e.message)}finally{input.disabled=false;input.focus()}};
connect();refresh();return()=>{events?.close();clearInterval(poll)};
}};
