window.MeetApp={id:'meet',name:'Meet',description:'Private one-to-one video calls with real browser connections.',icon:'assets/icons/neon/call.png',width:960,height:680,mount(body){
body.innerHTML=`<div class="meet-app"><div class="meet-top"><div><span class="eyebrow">NOVA MEET</span><h2>Face-to-face, private by design.</h2><p class="meet-sub">Create a temporary room and share its code. The room disappears when the call ends.</p></div><span class="meet-status" id="meet-status">Ready</span></div><div id="meet-setup" class="meet-setup"><div class="meet-card meet-create-card"><div class="meet-icon">◉</div><h3>Start a new call</h3><p>Nova will ask for camera and microphone access before opening your room.</p><button class="app-button meet-primary" id="meet-create">Create private call</button></div><div class="meet-card"><div class="meet-icon">↗</div><h3>Join with a code</h3><p>Enter the six-character code from the person hosting the call.</p><div class="meet-join"><input id="meet-code" maxlength="6" placeholder="ABC123"><button class="app-button" id="meet-join">Join</button></div></div></div><div id="meet-room" class="meet-room hidden"><div class="meet-room-head"><div><strong>PRIVATE ROOM</strong><code id="meet-room-code">------</code></div><button class="app-button" id="meet-copy">Copy code</button><button class="app-button danger" id="meet-leave">Leave</button></div><div class="meet-videos"><div class="meet-video"><video id="local-video" autoplay playsinline muted></video><span>You</span></div><div class="meet-video hidden" id="remote-wrap"><video id="remote-video" autoplay playsinline></video><span>Guest</span></div><div class="meet-wait" id="meet-wait">Waiting for someone to join…<small>Share the room code above.</small></div></div><div class="meet-call-controls"><button id="meet-mute" title="Mute microphone">🎙</button><button id="meet-camera" title="Turn camera off">▣</button><button id="meet-reconnect" title="Reconnect">↻</button></div><div class="meet-permissions" id="meet-perm">Camera and microphone are requested when you start or join.</div></div></div>`;
const setup=body.querySelector('#meet-setup'),room=body.querySelector('#meet-room'),status=body.querySelector('#meet-status'),localV=body.querySelector('#local-video'),remoteV=body.querySelector('#remote-video'),remoteWrap=body.querySelector('#remote-wrap'),wait=body.querySelector('#meet-wait'),perm=body.querySelector('#meet-perm'),muteBtn=body.querySelector('#meet-mute'),cameraBtn=body.querySelector('#meet-camera'),reconnectBtn=body.querySelector('#meet-reconnect');let stream=null,pc=null,role='',code='',events=null,remoteDescriptionSet=false,candidateQueue=[];
async function media(){if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera/microphone are unavailable. Use localhost or HTTPS.');try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});localV.srcObject=stream;perm.textContent='Camera and microphone are active.'}catch{throw Error('Camera or microphone permission was denied.')}}
function sendSignal(data){return NovaAuth.api('/api/meet/signal',{method:'POST',body:JSON.stringify({code,data})}).catch(()=>{})}
function setupPeer(){if(pc)try{pc.close()}catch{};pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{remoteV.srcObject=e.streams[0];remoteWrap.classList.remove('hidden');wait.classList.add('hidden');perm.textContent='Connected. Your camera and microphone are live.'};pc.onicecandidate=e=>{if(e.candidate)sendSignal({candidate:e.candidate})};pc.onconnectionstatechange=()=>{if(['failed','disconnected','closed'].includes(pc.connectionState))perm.textContent='Connection ended.'}}
async function handleSignal(data){if(!pc)return;if(data.candidate){if(remoteDescriptionSet)await pc.addIceCandidate(data.candidate).catch(()=>{});else candidateQueue.push(data.candidate);return}if(data.description){await pc.setRemoteDescription(data.description);remoteDescriptionSet=true;for(const c of candidateQueue)await pc.addIceCandidate(c).catch(()=>{});candidateQueue=[];if(data.description.type==='offer'){const a=await pc.createAnswer();await pc.setLocalDescription(a);await sendSignal({description:pc.localDescription})}}}
function listen(){events=NovaAuth.events(async m=>{if(m.type==='meet:peer-joined'&&role==='host'){setupPeer();const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal({description:pc.localDescription})}if(m.type==='meet:signal')await handleSignal(m.data);if(m.type==='meet:left'){OS.toast('The other person left the call.');cleanup()}})}
async function create(){try{await media();const d=await NovaAuth.api('/api/meet/create',{method:'POST'});role='host';code=d.code;listen();showRoom();status.textContent='Waiting for guest'}catch(e){OS.toast(e.message);cleanup()}}
async function join(){const c=body.querySelector('#meet-code').value.trim().toUpperCase();if(c.length!==6)return OS.toast('Enter the six-character call code.');try{await media();role='guest';code=c;setupPeer();listen();await NovaAuth.api('/api/meet/join',{method:'POST',body:JSON.stringify({code:c})});showRoom();status.textContent='Joining…'}catch(e){OS.toast(e.message);cleanup()}}
function showRoom(){setup.classList.add('hidden');room.classList.remove('hidden');body.querySelector('#meet-room-code').textContent=code;localV.srcObject=stream}
async function cleanup(){try{if(code)await NovaAuth.api('/api/meet/leave',{method:'POST',body:JSON.stringify({code})})}catch{}events?.close();events=null;try{pc?.close()}catch{}pc=null;stream?.getTracks().forEach(t=>t.stop());stream=null;remoteDescriptionSet=false;candidateQueue=[];code='';role='';room.classList.add('hidden');setup.classList.remove('hidden');status.textContent='Ready';remoteV.srcObject=null;remoteWrap.classList.add('hidden');wait.classList.remove('hidden');wait.innerHTML='Waiting for someone to join…<small>Share the room code above.</small>';perm.textContent='Camera and microphone are requested when you start or join.'}
muteBtn.onclick=()=>{const t=stream?.getAudioTracks?.()[0];if(!t)return;t.enabled=!t.enabled;muteBtn.classList.toggle('active',!t.enabled);muteBtn.textContent=t.enabled?'🎙':'🔇';perm.textContent=t.enabled?'Microphone on':'Microphone muted'};cameraBtn.onclick=()=>{const t=stream?.getVideoTracks?.()[0];if(!t)return;t.enabled=!t.enabled;cameraBtn.classList.toggle('active',!t.enabled);cameraBtn.textContent=t.enabled?'▣':'◌';perm.textContent=t.enabled?'Camera on':'Camera off'};reconnectBtn.onclick=async()=>{if(!stream||!code)return;try{setupPeer();if(role==='host'){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal({description:pc.localDescription})}else{await NovaAuth.api('/api/meet/join',{method:'POST',body:JSON.stringify({code})})};perm.textContent='Reconnecting…'}catch(e){OS.toast('Reconnect failed')}};body.querySelector('#meet-create').onclick=create;body.querySelector('#meet-join').onclick=join;body.querySelector('#meet-leave').onclick=cleanup;body.querySelector('#meet-copy').onclick=async()=>{try{await navigator.clipboard.writeText(code);OS.toast('Call code copied')}catch{OS.toast('Copy failed')}};return cleanup;
}};
