window.NOVA_MOVIES = window.NOVA_MOVIES || [];
window.MoviesApp={id:'movies',name:'Nova Watch',description:'A polished movie discovery and watching experience.',icon:'assets/icons/neon/movies.png',width:1120,height:760,mount(body){
 const movies=[];
 async function request(path,opts={}){const r=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||'Request failed');Object.assign(e,d);throw e}return d}
 async function serverIsOnline(){if(location.protocol==='file:'||!navigator.onLine)return false;try{const r=await fetch('/api/status',{cache:'no-store',credentials:'same-origin'});if(!r.ok)return false;const d=await r.json();return d.online!==false}catch{return false}}
 const originalMovies=Array.isArray(window.NOVA_MOVIES)?window.NOVA_MOVIES.slice():[];
 const moviesAccessMessage=mode=>{const text=mode==='guest'?'The Nova server is offline. Guest mode can use Nova Watch when the server is online.':'The Nova server is offline. Nova Watch requires the server for account access.';body.innerHTML=`<div class="movies-app"><div class="media-empty movie-access-message"><div class="empty-icon">☁</div><h2>Nova Watch is unavailable</h2><p>${text}</p><small>Developer bypass can still use Nova Watch while the server is offline.</small></div></div>`};
 const watchedKey='watched-movies',favKey='favorite-movies',playsKey='movie-plays';let view='home',activeCategory='All';
 const shows=[];const originalShows=Array.isArray(window.NOVA_SHOWS)?window.NOVA_SHOWS.slice():[];let activeShowSeason={};
 const posterFallback=(title,extraClass='')=>`<div class="show-poster-fallback ${extraClass}"><span>▣</span><strong>${esc(title||'Show')}</strong></div>`;
 const showPoster=(show,extraClass='')=>{const src=String(show.poster||'').trim();if(!src)return posterFallback(show.title,extraClass);const fallback=src.replace('/original/','/w500/');return `<img class="show-poster-img ${extraClass}" src="${esc(src)}" data-fallback="${esc(fallback)}" data-title="${esc(show.title||'Show')}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="if(this.dataset.fallback && this.src!==this.dataset.fallback){this.src=this.dataset.fallback;this.dataset.fallback='';}else{this.outerHTML='<div class=&quot;show-poster-fallback ${extraClass}&quot;><span>▣</span><strong>'+this.dataset.title+'</strong></div>'}">`;};
 const showCard=show=>`<article class="media-card show-card" data-show="${esc(show.id)}"><div class="show-poster-wrap">${showPoster(show)}<span class="show-badge">SHOW</span>${window.NovaAuthMode==='dev'?`<button class="media-dev-menu" data-show-dev-menu="${esc(show.id)}" aria-label="Show options">⋯</button>`:''}<button class="show-open" data-show-details="${esc(show.id)}">View show</button></div><div class="show-card-gradient"></div><div class="show-card-info"><h3>${esc(show.title||'Untitled')}</h3><p>${esc([show.year,show.maturityRating,show.genre].filter(Boolean).join(' • '))}</p></div></article>`;
 const validSeasons=show=>Array.isArray(show.seasons)?show.seasons.map((season,i)=>({number:Number(season.number||i+1),episodes:Math.max(0,Number(season.episodes||season.episodeCount||0))})).filter(s=>Number.isFinite(s.number)&&s.number>0&&s.episodes>0):[];
 const episodeUrl=(show,season,episode)=>`https://cinesrc.st/embed/tv/${encodeURIComponent(show.tmdbId)}?s=${encodeURIComponent(season)}&e=${encodeURIComponent(episode)}`;
 const showDetails=show=>{
   const old=document.getElementById('nova-show-details');if(old)old.remove();
   const seasons=validSeasons(show);if(!seasons.length){OS.toast('This show does not have any episode counts yet');return}
   const selected=seasons.find(s=>s.number===activeShowSeason[show.id])||seasons[0];activeShowSeason[show.id]=selected.number;
   const overlay=document.createElement('div');overlay.id='nova-show-details';overlay.className='movie-details-overlay show-details-overlay';
   const seasonButtons=seasons.map(s=>`<button class="show-season ${s.number===selected.number?'active':''}" data-season="${s.number}">Season ${s.number}</button>`).join('');
   const episodeButtons=Array.from({length:selected.episodes},(_,i)=>`<button class="show-episode" data-episode="${i+1}"><span>EPISODE ${i+1}</span><strong>${esc(show.title||'Show')} · S${selected.number} E${i+1}</strong><small>Play episode</small></button>`).join('');
   const cats=(show.categories||[]).map(c=>`<span>${esc(c)}</span>`).join('');
   overlay.innerHTML=`<div class="show-details-card" role="dialog" aria-modal="true"><div class="show-details-art">${showPoster(show)}<div class="show-details-shade"></div></div><button class="movie-details-close" aria-label="Close">×</button><div class="show-details-content"><span class="media-eyebrow">NOVA WATCH • SHOW</span><h1>${esc(show.title||'Untitled')}</h1><div class="movie-details-meta"><span>${esc(show.maturityRating||'NR')}</span><span>${esc(show.year||'Year unknown')}</span><span>${esc(show.genre||'TV Show')}</span><span>${seasons.length} season${seasons.length===1?'':'s'}</span></div><div class="movie-category-tags">${cats}</div><p class="movie-details-description">${esc(show.description||'Description not provided yet.')}</p><section class="show-episodes"><div class="show-episodes-heading"><div><span class="media-eyebrow">WATCH EPISODES</span><h2>Choose a season and episode</h2></div><span class="show-autoplay-note">Autoplay enabled</span></div><div class="show-seasons">${seasonButtons}</div><div class="show-episode-list">${episodeButtons}</div></section></div></div>`;
   body.appendChild(overlay);
   const close=()=>overlay.remove();overlay.querySelector('.movie-details-close').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};
   overlay.querySelectorAll('[data-season]').forEach(btn=>btn.onclick=()=>{activeShowSeason[show.id]=Number(btn.dataset.season);showDetails(show)});
   overlay.querySelectorAll('[data-episode]').forEach(btn=>btn.onclick=()=>{const ep=Number(btn.dataset.episode);close();playShowEpisode(show,selected.number,ep)});
   overlay.querySelector('.show-episode')?.focus();
 };
 const showSection=()=>{
   body.querySelectorAll('.movies-nav nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='shows'));
   const content=body.querySelector('.movies-content');if(!content)return;
   if(!shows.length){content.innerHTML=`<div class="shows-empty-page"><div class="shows-empty-icon">▣</div><span class="media-eyebrow">NOVA WATCH • SHOWS</span><h1>Shows are coming soon.</h1><p>Shows are not currently available yet. Add a show to <code>data/shows.js</code> when you're ready to start building the library.</p><div class="shows-empty-status"><span></span>Currently not available</div></div>`;return}
   content.innerHTML=`<section class="shows-page-hero"><div><span class="media-eyebrow">NOVA WATCH • SHOWS</span><h1>Your shows, seasons and episodes.</h1><p>Pick a show, choose a season, then select an episode. Nova generates the CineSRC episode link automatically.</p></div></section><section class="movie-section"><div class="movie-section-title"><div><span class="media-eyebrow">SHOW LIBRARY</span><h2>Shows</h2></div></div><div class="movie-grid media-grid shows-grid">${shows.map(showCard).join('')}</div></section>`;
   content.querySelectorAll('[data-show-details]').forEach(b=>b.onclick=e=>{e.stopPropagation();const show=shows.find(x=>String(x.id)===String(b.dataset.show));if(show)showDetails(show)});
   content.querySelectorAll('[data-show]').forEach(c=>c.onclick=e=>{if(e.target.closest('button'))return;const show=shows.find(x=>String(x.id)===String(c.dataset.show));if(show)showDetails(show)});
 };
 const watched=()=>Store.load(watchedKey,[]),favs=()=>Store.load(favKey,[]),plays=()=>Store.load(playsKey,{});
 const saveWatched=m=>{const a=watched();Store.save(watchedKey,[{id:m.id,title:m.title,genre:m.genre,at:Date.now()},...a.filter(x=>x.id!==m.id)].slice(0,50))};
 const isFav=id=>favs().includes(id);function toggleFav(id){const a=favs();Store.save(favKey,a.includes(id)?a.filter(x=>x!==id):[...a,id]);render()}
 function bumpPlay(id){const p=plays();p[id]=(p[id]||0)+1;Store.save(playsKey,p)}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const driveFileId=url=>{const s=String(url||'').trim();if(!s)return '';for(const p of [/drive\.google\.com\/file\/d\/([^/?]+)/i,/drive\.google\.com\/uc\?[^#]*id=([^&]+)/i,/drive\.google\.com\/open\?[^#]*id=([^&]+)/i]){const m=s.match(p);if(m)return decodeURIComponent(m[1])}return ''};
 const embedUrl=value=>{const s=String(value||'').trim();if(!s)return '';const iframe=s.match(/<iframe[^>]+src=["']([^"']+)["'][^>]*>/i);const u=iframe?iframe[1]:s;if(/drive\.google\.com\/file\/d\//i.test(u)){const id=driveFileId(u);return id?`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview?usp=embed`:u}return u};
 async function loadShows(){try{const response=await fetch('/api/content/shows',{cache:'no-store',credentials:'include'});if(!response.ok)throw new Error();const source=await response.json();const map=new Map(originalShows.map(x=>[String(x.id||x.tmdbId),x]));(Array.isArray(source)?source:[]).forEach(x=>{const base=map.get(String(x.id||x.tmdbId))||{};map.set(String(x.id||x.tmdbId),{...base,...x,poster:String(x.poster||base.poster||'').trim()})});shows.splice(0,shows.length,...map.values());if(view==='shows')showSection()}catch{shows.splice(0,shows.length,...originalShows);if(view==='shows')showSection()}}
 async function loadMovies(){let source=[];try{const response=await fetch('/api/content/movies',{cache:'no-store',credentials:'include'});if(!response.ok)throw new Error('server-offline');source=await response.json()}catch(e){if(window.NovaAuthMode==='dev'&&originalMovies.length){movies.splice(0,movies.length,...originalMovies);window.NOVA_MOVIES=movies;render();return}movies.splice(0,movies.length);const el=body.querySelector('.movies-content');if(el)el.innerHTML='<div class="media-empty"><div class="empty-icon">☁</div><h2>Nova Watch is unavailable</h2><p>The Nova server is offline. Developer bypass can still open Nova Watch, but the server catalog could not be loaded.</p></div>';return}
   const normalized=source.map((m,i)=>{const item={...m};let value=item.embed||item.iframe||item.embedUrl||item.driveUrl||item.url||'';const iframe=String(value).match(/<iframe[^>]+src=["']([^"']+)["'][^>]*>/i);if(iframe)value=iframe[1];item.id=item.id||`movie-${i+1}`;item.title=item.title||`Movie ${i+1}`;item.embedUrl=embedUrl(value);item.categories=Array.isArray(item.categories)&&item.categories.length?item.categories:[item.genre||'Popular'];item.maturityRating=item.maturityRating||'NR';item.description=item.description||'Description not provided yet.';return item}).filter(m=>m.embedUrl);
   const map=new Map(originalMovies.map(m=>[String(m.id||m.title),m]));normalized.forEach(m=>map.set(String(m.id||m.title),{...map.get(String(m.id||m.title)),...m}));const merged=[...map.values()].filter(m=>m&&(m.embedUrl||m.embed||m.driveUrl||m.url));window.NOVA_MOVIES=merged;movies.splice(0,movies.length,...merged);render();
 }
 function allCategories(){const set=new Set();movies.forEach(m=>(Array.isArray(m.categories)?m.categories:[m.genre]).filter(Boolean).forEach(c=>set.add(String(c))));return ['All',...Array.from(set).sort((a,b)=>a.localeCompare(b))]}
 function categoryMatch(m){return activeCategory==='All'||(Array.isArray(m.categories)?m.categories:[m.genre]).some(c=>String(c).toLowerCase()===activeCategory.toLowerCase())}
 function sameGenre(m){const gs=(Array.isArray(m.categories)?m.categories:[m.genre]).map(x=>String(x).toLowerCase());return movies.filter(x=>x.id!==m.id&&(Array.isArray(x.categories)?x.categories:[x.genre]).some(g=>gs.includes(String(g).toLowerCase())))}
 function card(m){const fav=isFav(m.id),dev=window.NovaAuthMode==='dev';const poster=m.poster?`<img class="media-poster-img" src="${esc(m.poster)}" alt="">`:`<div class="media-poster generated-poster"><span>🎬</span><strong>${esc(m.title||'Movie')}</strong></div>`;const cats=(m.categories||[]).slice(0,2).join(' • ');return `<article class="media-card movie-card" data-movie="${esc(m.id)}"><div class="movie-poster-wrap">${poster}<button class="movie-fav ${fav?'on':''}" data-fav="${esc(m.id)}" aria-label="${fav?'Remove from favorites':'Add to favorites'}">${fav?'★':'☆'}</button>${dev?`<button class="media-dev-menu" data-dev-menu="${esc(m.id)}" aria-label="Movie options">⋯</button>`:''}<button class="movie-open" data-details="${esc(m.id)}">View details</button></div><div class="movie-card-gradient"></div><div class="movie-card-info"><h3>${esc(m.title||'Untitled')}</h3><p>${esc([m.year,m.maturityRating,cats].filter(Boolean).join(' • '))}</p></div></article>`}
function editMovie(m){if(window.NovaAuthMode!=='dev')return;const overlay=document.createElement('div');overlay.className='dev-edit-overlay';overlay.innerHTML=`<div class="dev-edit-card"><div class="dev-edit-head"><div><span class="media-eyebrow">DEVELOPER EDITOR</span><h2>Edit movie</h2></div><button class="movie-details-close" id="dev-edit-close">×</button></div><div class="dev-edit-grid"><label>Movie name<input id="em-title" value="${esc(m.title||'')}"></label><label>TMDB ID<input id="em-tmdb" value="${esc(m.tmdbId||m.id||'')}"></label><label>Poster link<input id="em-poster" value="${esc(m.poster||'')}"></label><label>Year<input id="em-year" type="number" value="${esc(m.year||'')}"></label><label>Maturity rating<input id="em-rating" value="${esc(m.maturityRating||'')}"></label><label>Genre<input id="em-genre" value="${esc(m.genre||'')}"></label><label class="dev-edit-wide">Categories<input id="em-cats" value="${esc((m.categories||[]).join(', '))}"></label><label class="dev-edit-wide">Description<textarea id="em-desc" rows=5>${esc(m.description||'')}</textarea></label></div><div class="dev-edit-actions"><button class="movie-secondary" id="dev-edit-cancel">Cancel</button><button class="hero-button" id="dev-edit-save">Save changes</button></div></div>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('#dev-edit-close').onclick=close;overlay.querySelector('#dev-edit-cancel').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};overlay.querySelector('#dev-edit-save').onclick=async()=>{try{const b={id:m.id,title:overlay.querySelector('#em-title').value.trim(),tmdbId:overlay.querySelector('#em-tmdb').value.trim(),poster:overlay.querySelector('#em-poster').value.trim(),year:overlay.querySelector('#em-year').value, maturityRating:overlay.querySelector('#em-rating').value.trim(),genre:overlay.querySelector('#em-genre').value.trim(),categories:overlay.querySelector('#em-cats').value.split(',').map(x=>x.trim()).filter(Boolean),description:overlay.querySelector('#em-desc').value.trim()};await request('/api/dev/update-movie',{method:'POST',body:JSON.stringify(b)});OS.toast('Movie updated for everyone');close();loadMovies()}catch(e){OS.toast(e.message)}}}
function deleteMovie(m){if(window.NovaAuthMode!=='dev')return;if(!confirm(`Delete “${m.title}” from Nova Watch for everyone?`))return;request('/api/dev/delete-movie',{method:'POST',body:JSON.stringify({id:m.id})}).then(()=>{OS.toast('Movie deleted for everyone');loadMovies()}).catch(e=>OS.toast(e.message))}
 function section(title,items,eyebrow='NOVA WATCH'){if(!items.length)return '';return `<section class="movie-section"><div class="movie-section-title"><div><span class="media-eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div></div><div class="movie-grid media-grid">${items.map(card).join('')}</div></section>`}
 function render(){if(view==='shows'){showSection();return}const history=watched(),first=history.length?movies.find(m=>m.id===history[0].id):null;const q=(body.querySelector('#movie-search')?.value||'').trim().toLowerCase();let list=movies.filter(m=>categoryMatch(m)&&(m.title+' '+(m.genre||'')+' '+(m.categories||[]).join(' ')+' '+(m.year||'')).toLowerCase().includes(q));if(view==='library')list=movies.filter(m=>isFav(m.id));const recent=history.map(x=>movies.find(m=>m.id===x.id)).filter(Boolean);const because=first?sameGenre(first).filter(m=>!history.some(x=>x.id===m.id)).slice(0,8):[];const p=plays();const trending=[...movies].sort((a,b)=>(p[b.id]||0)-(p[a.id]||0)).slice(0,8);const newer=[...movies].sort((a,b)=>Number(b.year||0)-Number(a.year||0)).slice(0,8);const favorites=movies.filter(m=>isFav(m.id));const categories=allCategories();
  if(view==='movies'){body.querySelector('.movies-content').innerHTML=`<div class="all-movies-hero"><div><span class="media-eyebrow">NOVA WATCH • LIBRARY</span><h1>All Movies</h1><p>Every movie currently available in Nova Watch, in one place.</p></div><strong>${movies.length} titles</strong></div><div class="movie-category-bar">${categories.map(c=>`<button class="movie-category ${c===activeCategory?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div>${section('Every movie',list,'FULL CATALOG')}`;const search=body.querySelector('#movie-search');if(search)search.value=q;bind();return}
  body.querySelector('.movies-content').innerHTML=`<div class="movie-category-bar">${categories.map(c=>`<button class="movie-category ${c===activeCategory?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div>${view==='library'?section('Your Favorites',list,'MY LIBRARY'):q?section('Search results',list,'SEARCH'):activeCategory!=='All'?section(activeCategory,list,'CATEGORY'): `<section class="movie-hero" id="movie-hero"><div class="hero-copy"><span class="media-eyebrow">NOVA WATCH</span><h1>Movies made for<br>your night.</h1><p>Discover, explore, and choose what you want to watch.</p><button id="hero-play" class="hero-button">▶ ${movies.length?'Surprise me':'Explore'}</button></div></section>${section('Continue Watching',recent,'KEEP WATCHING')}${first?section('Because you watched '+first.title,because,'RECOMMENDED FOR YOU'):''}${section('Trending',trending,'POPULAR RIGHT NOW')}${section('New',newer,'JUST ADDED')}${section('Your Favorites',favorites,'YOUR LIBRARY')}${categories.filter(c=>c!=='All').slice(0,6).map(c=>section(c,movies.filter(m=>(m.categories||[]).includes(c)).slice(0,8),'BROWSE BY CATEGORY')).join('')}`}${!movies.length?`<div class="media-empty"><div class="empty-icon">🎬</div><h2>No movies yet</h2><p>Add movies to <code>data/movies.js</code> in the project.</p></div>`:''}`;
  const search=body.querySelector('#movie-search');if(search)search.value=q;bind();const hero=body.querySelector('#movie-hero');const heroMovie=trending[0]||movies[0];if(hero&&heroMovie?.poster)hero.style.backgroundImage=`linear-gradient(90deg,rgba(4,7,14,.98) 0%,rgba(4,7,14,.84) 42%,rgba(4,7,14,.28) 78%,rgba(4,7,14,.08)),url("${String(heroMovie.poster).replace(/"/g,'&quot;')}")`;const heroPlay=body.querySelector('#hero-play');if(heroPlay)heroPlay.onclick=()=>movies.length?details(heroMovie||movies[0]):null;
 }

 function editShow(show){if(window.NovaAuthMode!=='dev')return;const overlay=document.createElement('div');overlay.className='dev-edit-overlay';overlay.innerHTML=`<div class="dev-edit-card"><div class="dev-edit-head"><div><span class="media-eyebrow">SHOW EDITOR</span><h2>Edit ${esc(show.title||'Show')}</h2></div><button class="movie-details-close">×</button></div><div class="dev-edit-grid"><label>Show name<input id="es-title" value="${esc(show.title||'')}"></label><label>TMDB ID<input id="es-tmdb" value="${esc(show.tmdbId||'')}"></label><label>Poster link<input id="es-poster" value="${esc(show.poster||'')}"></label><label>Year<input id="es-year" type="number" value="${esc(show.year||'')}"></label><label>Maturity rating<input id="es-rating" value="${esc(show.maturityRating||'')}"></label><label>Genre<input id="es-genre" value="${esc(show.genre||'')}"></label><label class="dev-edit-wide">Categories<input id="es-cats" value="${esc((show.categories||[]).join(', '))}"></label><label class="dev-edit-wide">Seasons<input id="es-seasons" value="${esc((show.seasons||[]).map(s=>`${s.number}:${s.episodes}`).join(', '))}" placeholder="1:10, 2:8"></label><label class="dev-edit-wide">Description<textarea id="es-desc" rows="5">${esc(show.description||'')}</textarea></label></div><div class="dev-edit-actions"><button class="app-button" id="es-cancel">Cancel</button><button class="app-button dev-primary" id="es-save">Save show</button></div></div>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.movie-details-close').onclick=close;overlay.querySelector('#es-cancel').onclick=close;overlay.querySelector('#es-save').onclick=async()=>{try{const seasons=overlay.querySelector('#es-seasons').value.split(',').map((x,i)=>{const [n,e]=x.trim().split(':').map(Number);return{number:n||i+1,episodes:e||0}}).filter(x=>x.episodes>0);await request('/api/dev/update-show',{method:'POST',body:JSON.stringify({id:show.id,title:overlay.querySelector('#es-title').value.trim(),tmdbId:overlay.querySelector('#es-tmdb').value.trim(),poster:overlay.querySelector('#es-poster').value.trim(),year:overlay.querySelector('#es-year').value,maturityRating:overlay.querySelector('#es-rating').value.trim(),genre:overlay.querySelector('#es-genre').value.trim(),categories:overlay.querySelector('#es-cats').value.split(',').map(x=>x.trim()).filter(Boolean),seasons,description:overlay.querySelector('#es-desc').value.trim()})});OS.toast('Show updated for everyone');close();await loadShows()}catch(e){OS.toast(e.message)}}}
 function deleteShow(show){if(window.NovaAuthMode!=='dev')return;if(!confirm(`Delete “${show.title}” from Nova Watch for everyone?`))return;request('/api/dev/delete-show',{method:'POST',body:JSON.stringify({id:show.id})}).then(()=>{OS.toast('Show deleted for everyone');loadShows()}).catch(e=>OS.toast(e.message))}
 function bind(){body.querySelectorAll('[data-details]').forEach(b=>b.onclick=e=>{e.stopPropagation();const m=movies.find(x=>x.id===b.dataset.details);if(m)details(m)});body.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});body.querySelectorAll('[data-dev-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();const m=movies.find(x=>x.id===b.dataset.devMenu);if(!m)return;const menu=document.createElement('div');menu.className='media-dev-popover';menu.innerHTML='<button data-edit>✎ Edit</button><button data-delete>⌫ Delete</button>';b.parentElement.appendChild(menu);menu.querySelector('[data-edit]').onclick=()=>{menu.remove();editMovie(m)};menu.querySelector('[data-delete]').onclick=()=>{menu.remove();deleteMovie(m)};setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0)});body.querySelectorAll('[data-show-dev-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();const show=shows.find(x=>String(x.id)===String(b.dataset.showDevMenu));if(!show)return;const menu=document.createElement('div');menu.className='media-dev-popover';menu.innerHTML='<button data-edit>✎ Edit</button><button data-delete>⌫ Delete</button>';b.parentElement.appendChild(menu);menu.querySelector('[data-edit]').onclick=()=>{menu.remove();editShow(show)};menu.querySelector('[data-delete]').onclick=()=>{menu.remove();deleteShow(show)};setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0)});body.querySelectorAll('.movie-card').forEach(c=>c.onclick=e=>{if(e.target.closest('button'))return;const m=movies.find(x=>x.id===c.dataset.movie);if(m)details(m)});const search=body.querySelector('#movie-search');if(search)search.oninput=render;body.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;render()})}
 function details(m){const old=document.getElementById('nova-movie-details');if(old)old.remove();const overlay=document.createElement('div');overlay.id='nova-movie-details';overlay.className='movie-details-overlay';const poster=m.poster?`<img src="${esc(m.poster)}" alt="">`:'<div class="movie-details-poster-fallback">🎬</div>';const cats=(m.categories||[]).map(c=>`<span>${esc(c)}</span>`).join('');overlay.innerHTML=`<div class="movie-details-card" role="dialog" aria-modal="true"><div class="movie-details-art">${poster}<div class="movie-details-shade"></div></div><button class="movie-details-close" aria-label="Close">×</button><div class="movie-details-content"><span class="media-eyebrow">NOVA WATCH</span><h1>${esc(m.title||'Untitled')}</h1><div class="movie-details-meta"><span>${esc(m.maturityRating||'NR')}</span><span>${esc(m.year||'Year unknown')}</span><span>${esc(m.genre||'Movie')}</span></div><div class="movie-category-tags">${cats}</div><p class="movie-details-description">${esc(m.description||'Description not provided yet.')}</p><div class="movie-details-actions"><button class="hero-button" id="movie-start">▶ Watch now</button><button class="movie-secondary" id="movie-detail-fav">${isFav(m.id)?'★ Favorited':'☆ Add to favorites'}</button></div></div></div>`;body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.movie-details-close').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};overlay.querySelector('#movie-start').onclick=()=>{close();play(m)};overlay.querySelector('#movie-detail-fav').onclick=()=>{toggleFav(m.id);const b=overlay.querySelector('#movie-detail-fav');b.textContent=isFav(m.id)?'★ Favorited':'☆ Add to favorites'};overlay.querySelector('#movie-start').focus()}
 function playShowEpisode(show,season,episode){
   const url=episodeUrl(show,season,episode);const overlay=document.createElement('div');overlay.className='movie-player-overlay show-player-overlay';
   const currentLabel=`Season ${season} · Episode ${episode}`;const seasons=validSeasons(show);const seasonIndex=seasons.findIndex(s=>s.number===season);const currentSeason=seasons[seasonIndex];const nextEpisode=episode<currentSeason.episodes?{season,episode:episode+1}:seasonIndex<seasons.length-1?{season:seasons[seasonIndex+1].number,episode:1}:null;
   overlay.innerHTML=`<div class="movie-player show-player"><div class="movie-player-backdrop"></div><div class="movie-player-bar"><div><span class="media-eyebrow">NOW WATCHING</span><strong>${esc(show.title||'Show')} · ${esc(currentLabel)}</strong></div><div class="movie-player-actions"><button id="player-fullscreen" title="Fullscreen">⛶</button><button id="player-close" aria-label="Close">×</button></div></div><div class="movie-player-stage"><iframe id="show-frame" title="Nova Watch show player" allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowfullscreen loading="eager" referrerpolicy="strict-origin-when-cross-origin" src="${esc(url)}"></iframe></div><div class="movie-player-meta"><span>${esc([show.year,show.maturityRating,show.genre,currentLabel].filter(Boolean).join(' • '))}</span><span class="show-player-autoplay">Autoplay on</span></div></div>`;
   const stage=overlay.querySelector('.movie-player-stage'),frame=overlay.querySelector('#show-frame');overlay.querySelector('.movie-player-backdrop').style.backgroundImage=show.poster?`linear-gradient(90deg,rgba(5,8,15,.96),rgba(5,8,15,.15)),url("${show.poster}")`:'';
   const fullscreen=()=>{try{if(document.fullscreenElement)document.exitFullscreen();else if(stage.requestFullscreen)stage.requestFullscreen()}catch{OS.toast('Fullscreen is not available in this browser.')}};overlay.querySelector('#player-fullscreen').onclick=fullscreen;
   let closed=false;const close=()=>{if(closed)return;closed=true;window.removeEventListener('message',onMessage);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});if(frame)frame.src='about:blank';overlay.remove();};overlay.querySelector('#player-close').onclick=close;
   const onMessage=e=>{if(e.origin!=='https://cinesrc.st')return;const data=e.data;if((typeof data==='string'&&data==='cinesrc:ended')||(data&&data.type==='cinesrc:ended')||(data&&data.event==='cinesrc:ended')){if(nextEpisode){close();playShowEpisode(show,nextEpisode.season,nextEpisode.episode)}else{OS.toast('You finished the last episode of this show');}}};window.addEventListener('message',onMessage);body.appendChild(overlay);
 }
 function movieStage(m,url){const isDrive=!!driveFileId(url);if(isDrive){const id=driveFileId(url),stream=`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`,preview=`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview?usp=embed`;return `<div class="movie-native-wrap"><video id="movie-video" controls playsinline preload="metadata" crossorigin="anonymous"><source src="${esc(stream)}" type="video/mp4"></video><div class="movie-fallback" hidden><iframe id="movie-frame" title="Nova Watch movie player" allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowfullscreen loading="eager" referrerpolicy="strict-origin-when-cross-origin" src="${esc(preview)}"></iframe></div></div>`}return `<iframe id="movie-frame" title="Nova Watch movie player" allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowfullscreen loading="eager" referrerpolicy="strict-origin-when-cross-origin" src="${esc(url)}"></iframe>`}
 function play(m){const url=embedUrl(m.embedUrl||m.driveUrl||m.url);if(!url){OS.toast('This movie does not have an embed link yet');return}saveWatched(m);bumpPlay(m.id);const overlay=document.createElement('div');overlay.className='movie-player-overlay';overlay.innerHTML=`<div class="movie-player"><div class="movie-player-backdrop"></div><div class="movie-player-bar"><div><span class="media-eyebrow">NOW WATCHING</span><strong>${esc(m.title||'Movie')}</strong></div><div class="movie-player-actions"><button id="player-fullscreen" title="Fullscreen">⛶</button><button id="player-close" aria-label="Close">×</button></div></div><div class="movie-player-stage">${movieStage(m,url)}</div><div class="movie-player-meta"><span>${esc([m.year,m.maturityRating,m.genre].filter(Boolean).join(' • '))}</span><button id="player-fav">${isFav(m.id)?'★ Favorited':'☆ Favorite'}</button></div></div>`;overlay.querySelector('.movie-player-backdrop').style.backgroundImage=m.poster?`linear-gradient(90deg,rgba(5,8,15,.96),rgba(5,8,15,.15)),url("${m.poster}")`:'';const stage=overlay.querySelector('.movie-player-stage'),frame=overlay.querySelector('#movie-frame'),video=overlay.querySelector('#movie-video');
  const fullscreen=()=>{const target=stage;try{if(document.fullscreenElement)document.exitFullscreen();else if(target.requestFullscreen)target.requestFullscreen()}catch{OS.toast('Fullscreen is not available in this browser.')}};overlay.querySelector('#player-fullscreen').onclick=fullscreen;
  if(video)video.addEventListener('error',()=>{const fallback=overlay.querySelector('.movie-fallback');if(fallback){fallback.hidden=false;video.style.display='none'}});
  const close=()=>{if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});if(frame)frame.src='about:blank';if(video){video.pause();video.removeAttribute('src');video.load()}overlay.remove();render()};overlay.querySelector('#player-close').onclick=close;overlay.querySelector('#player-fav').onclick=()=>{toggleFav(m.id);overlay.querySelector('#player-fav').textContent=isFav(m.id)?'★ Favorited':'☆ Favorite'};body.appendChild(overlay);if(video)video.focus()}
 body.innerHTML=`<div class="movies-app"><header class="movies-nav"><div class="movies-brand"><span class="movies-mark">N</span><strong>Nova Watch</strong></div><nav><button class="active" data-view="home">Home</button><button data-view="movies">All Movies</button><button data-view="shows">Shows</button><button data-view="library">My Library</button></nav><label class="movies-search"><span>⌕</span><input id="movie-search" placeholder="Search movies"></label></header><main class="movies-content"></main></div>`;
 body.querySelector('[data-view="movies"]').onclick=()=>{view='movies';body.querySelectorAll('.movies-nav nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='movies'));activeCategory='All';render()};
 body.querySelector('[data-view="shows"]').onclick=()=>{view='shows';showSection()};
 body.querySelector('[data-view="home"]').onclick=()=>{view='home';body.querySelectorAll('.movies-nav nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='home'));render()};
 body.querySelector('[data-view="library"]').onclick=()=>{view='library';body.querySelectorAll('.movies-nav nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='library'));render()};
 (async()=>{if(window.NovaAuthMode!=='dev'){const online=await serverIsOnline();if(!online){moviesAccessMessage(window.NovaAuthMode);return}}render();loadShows();loadMovies()})();return()=>{};
}};
