/* Developer-controlled local music library. Drop MP3s into assets/music/. The Nova server scans that folder automatically. */
window.NovaMusicLibrary=window.NovaMusicLibrary||[];
(function(){
  let audio=window.__novaMusicAudio,current=Number(localStorage.getItem('nova-os:music-current')||0),shuffle=false,repeat=false;
  function songs(){return window.NovaMusicLibrary||[]}
  function ensure(){if(!audio){audio=new Audio();audio.preload='metadata';window.__novaMusicAudio=audio;audio.addEventListener('ended',()=>{if(repeat){audio.currentTime=0;audio.play().catch(()=>{});return}next()});audio.addEventListener('timeupdate',()=>document.dispatchEvent(new CustomEvent('nova-music-time')))}return audio}
  async function refreshLibrary(){try{const r=await fetch('/api/content/music',{cache:'no-store'});if(!r.ok)return;const list=await r.json();if(Array.isArray(list)){window.NovaMusicLibrary=list;current=Math.min(current,Math.max(0,list.length-1));document.dispatchEvent(new CustomEvent('nova-music-library-change'))}}catch(e){console.warn('Nova Music catalog unavailable:',e.message)}}
  function load(i,autoplay=false){const list=songs();if(!list.length)return false;current=(i+list.length)%list.length;localStorage.setItem('nova-os:music-current',current);const s=list[current],a=ensure();a.src=s.src;a.volume=Number(localStorage.getItem('nova-os:music-volume')||.8);a.load();document.dispatchEvent(new CustomEvent('nova-music-change'));if(autoplay)a.play().catch(()=>{});return true}
  function play(){const a=ensure();if(!a.src&&!load(current,false))return;return a.play().then(()=>document.dispatchEvent(new CustomEvent('nova-music-change'))).catch(()=>{})}
  function pause(){ensure().pause();document.dispatchEvent(new CustomEvent('nova-music-change'))}function toggle(){ensure().paused?play():pause()}
  function next(){const list=songs();if(!list.length)return;if(shuffle)current=Math.floor(Math.random()*list.length);else current=(current+1)%list.length;load(current,true)}
  function prev(){const a=ensure();if(a.currentTime>3){a.currentTime=0;return}const list=songs();if(!list.length)return;load((current-1+list.length)%list.length,true)}
  function state(){const s=songs()[current]||{};return{id:s.id,title:s.title,artist:s.artist,playing:!!audio&&!audio.paused,current,duration:audio?.duration||0,time:audio?.currentTime||0}}
  window.NovaMusicEngine={load,play,pause,toggle,next,prev,state,audio:()=>ensure(),refreshLibrary,setVolume(v){localStorage.setItem('nova-os:music-volume',v);ensure().volume=v}};
  window.MusicApp={id:'music',name:'Music',description:'A clean Nova music player that keeps playing after the app closes',icon:'assets/icons/neon/music.png',width:820,height:600,mount(body){
    body.innerHTML=`<div class="music-app"><aside class="music-sidebar"><div class="music-brand"><span class="music-brand-icon">♫</span><div><strong>Nova Music</strong><small>Local library</small></div></div><button class="music-nav active">⌂ <span>Home</span></button><div class="music-sidebar-label">LIBRARY</div><div class="music-playlist-note" id="music-folder-note">Scanning assets/music/...</div></aside><main class="music-main"><header class="music-topbar"><div><span class="music-eyebrow">YOUR MUSIC</span><h2>Home</h2></div><input id="music-search" placeholder="Search your library"></header><section class="music-hero"><div class="music-cover">♫</div><div><span>LOCAL LIBRARY</span><h1>Nova Mix</h1><p>Drop MP3 files into <code>assets/music/</code> and Nova adds them automatically.</p><button class="music-primary" id="shuffle-all">▶ Shuffle Play</button></div></section><section class="music-section"><div class="music-section-head"><h3>All songs</h3><span id="song-count"></span></div><div id="music-list" class="music-list"></div></section></main><footer class="music-player"><div class="now-playing"><div class="mini-cover">♫</div><div><strong id="np-title">Nothing playing</strong><small id="np-artist">Choose a song</small></div></div><div class="player-center"><div class="player-controls"><button id="prev">‹‹</button><button id="play" class="play-main">▶</button><button id="next">››</button></div><div class="progress-row"><span id="cur-time">0:00</span><input id="progress" type="range" min="0" max="100" value="0"><span id="dur-time">0:00</span></div></div><div class="player-right"><button id="shuffle">⤨</button><button id="repeat">↻</button><input id="volume" type="range" min="0" max="1" step=".01" value=".8"></div></footer></div>`;
    const q=id=>body.querySelector('#'+id),fmt=x=>{x=Math.max(0,Math.floor(x||0));return Math.floor(x/60)+':'+String(x%60).padStart(2,'0')};let list=songs();
    function render(filter=''){list=songs();const rows=list.filter(s=>(s.title+' '+(s.artist||'')+' '+(s.album||'')).toLowerCase().includes(filter.toLowerCase()));q('song-count').textContent=list.length+' song'+(list.length===1?'':'s');q('music-folder-note').textContent=list.length?`${list.length} song${list.length===1?'':'s'} found in assets/music/`:'No MP3s found in assets/music/';q('music-list').innerHTML=rows.length?rows.map(s=>`<button class="music-track" data-id="${escapeHtml(s.id)}"><span class="track-number">▶</span><span class="track-cover">♫</span><span class="track-info"><strong>${escapeHtml(s.title)}</strong><small>${escapeHtml(s.artist||'Local file')}</small></span><span class="track-album">${escapeHtml(s.album||'')}</span><span class="track-play">▶</span></button>`).join(''):'<div class="music-empty"><div>♫</div><strong>Your library is empty</strong><p>Drop MP3 files into <code>assets/music/</code>. No code changes are needed.</p></div>';q('music-list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const i=list.findIndex(s=>s.id===b.dataset.id);load(i,true)})}
    function update(){const st=state();q('np-title').textContent=st.title||'Nothing playing';q('np-artist').textContent=st.artist||'Choose a song';q('play').textContent=st.playing?'Ⅱ':'▶';q('progress').value=st.duration?st.time/st.duration*100:0;q('cur-time').textContent=fmt(st.time);q('dur-time').textContent=fmt(st.duration)}
    q('play').onclick=toggle;q('next').onclick=next;q('prev').onclick=prev;q('shuffle').onclick=()=>shuffle=!shuffle;q('repeat').onclick=()=>repeat=!repeat;q('shuffle-all').onclick=()=>list.length&&load(Math.floor(Math.random()*list.length),true);q('volume').value=localStorage.getItem('nova-os:music-volume')||.8;q('volume').oninput=e=>NovaMusicEngine.setVolume(e.target.value);q('progress').oninput=e=>{const a=NovaMusicEngine.audio();if(a.duration)a.currentTime=Number(e.target.value)/100*a.duration};q('music-search').oninput=e=>render(e.target.value);
    const onChange=()=>update(),onLibrary=()=>render(q('music-search').value);document.addEventListener('nova-music-change',onChange);document.addEventListener('nova-music-time',onChange);document.addEventListener('nova-music-library-change',onLibrary);render();update();NovaMusicEngine.refreshLibrary();
    return()=>{document.removeEventListener('nova-music-change',onChange);document.removeEventListener('nova-music-time',onChange);document.removeEventListener('nova-music-library-change',onLibrary)};
  }};
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
