window.NovaWidgets=(()=>{
  const widgets={
    clock:{name:'Clock Widget',icon:'◷',requires:'clock'},
    music:{name:'Nova Music Widget',icon:'♫',requires:'music'},dailyBible:{name:'Daily Bible Verse',icon:'✝',requires:'bible'}
  };
  const key='desktop-widgets';
  const load=()=>Store.load(key,[]);
  const save=v=>Store.save(key,v);
  function panel(){
    if(Store.getSettings().experimental?.widgets===false){OS.toast('Widgets are disabled in Settings → Experimental');return}
    let p=document.getElementById('widgets-panel'); if(p){p.remove();return}
    p=document.createElement('aside');p.id='widgets-panel';p.className='widgets-panel';
    p.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><div><h3>Widgets</h3><p>Only installed apps can add widgets.</p></div><button class="icon-button" id="widget-panel-close">×</button></div><div class="widget-list">'+Object.entries(widgets).map(([id,w])=>`<button class="widget-add" data-widget="${id}"><span>${w.icon} <strong>${w.name}</strong><small>Requires ${OS.apps[w.requires]?.name||w.requires}</small></span><span>${load().includes(id)?'Added':'Add'}</span></button>`).join('')+'</div>';
    document.body.appendChild(p);p.querySelector('#widget-panel-close').onclick=()=>p.remove();
    p.querySelectorAll('[data-widget]').forEach(b=>b.onclick=()=>{const id=b.dataset.widget;if(!OS.isInstalled(widgets[id].requires)){OS.toast('Install '+OS.apps[widgets[id].requires].name+' first');return}const a=load();if(!a.includes(id))a.push(id);save(a);p.remove();render();OS.toast(widgets[id].name+' added')});
  }
  function remove(id){save(load().filter(x=>x!==id));render()}
  function clockWidget(){const el=document.createElement('section');el.className='desktop-widget';el.dataset.widget='clock';el.style.right='24px';el.style.top='24px';el.innerHTML='<div class="desktop-widget-head"><span>◷ CLOCK</span><button class="desktop-widget-close">×</button></div><div class="clock-widget-time">--:--</div><div class="clock-widget-date">---</div>';el.querySelector('button').onclick=()=>remove('clock');const tick=()=>{if(!el.isConnected)return;const s=Store.getSettings(),n=new Date();el.querySelector('.clock-widget-time').textContent=n.toLocaleTimeString([],s.clock24?{hour:'2-digit',minute:'2-digit'}:{hour:'numeric',minute:'2-digit'});el.querySelector('.clock-widget-date').textContent=n.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'});};tick();const timer=setInterval(tick,1000);el._cleanup=()=>clearInterval(timer);return el}
  function dailyBibleWidget(){const verses=[['John 3:16','For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.','A reminder that God’s love is offered freely and that faith is at the center of the Christian message.'],['Psalm 23:1','The LORD is my shepherd; I shall not want.','This points to God as a guide and provider, especially when life feels uncertain.'],['Proverbs 3:5','Trust in the LORD with all thine heart; and lean not unto thine own understanding.','It encourages trust in God while recognizing that we do not always see the whole picture.'],['Philippians 4:13','I can do all things through Christ which strengtheneth me.','The verse emphasizes finding strength through Christ when facing challenges.'],['Joshua 1:9','Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.','A message of courage: you do not have to face difficult moments as though you are alone.'],['Romans 12:12','Rejoicing in hope; patient in tribulation; continuing instant in prayer.','It gives a simple rhythm for difficult days: keep hope, be patient, and keep praying.'],['Psalm 46:10','Be still, and know that I am God.','A reminder to pause, quiet the noise, and remember God’s presence.']];const d=new Date(),idx=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000)%verses.length,v=verses[idx];const el=document.createElement('section');el.className='desktop-widget daily-bible-widget';el.dataset.widget='dailyBible';el.style.left='24px';el.style.bottom='104px';el.innerHTML='<div class="desktop-widget-head"><span>✝ DAILY VERSE</span><button class="desktop-widget-close">×</button></div><div class="daily-bible-ref">'+v[0]+'</div><div class="daily-bible-text">“'+v[1]+'”</div><div class="daily-bible-meaning"><strong>What it means</strong><span>'+v[2]+'</span></div><button class="daily-bible-open">Open Bible</button>';el.querySelector('.desktop-widget-close').onclick=()=>remove('dailyBible');el.querySelector('.daily-bible-open').onclick=()=>OS.launch('bible');return el}
  function musicWidget(){const el=document.createElement('section');el.className='desktop-widget music-widget';el.dataset.widget='music';el.style.left='24px';el.style.top='24px';el.innerHTML='<div class="desktop-widget-head"><span>♫ NOVA MUSIC</span><button class="desktop-widget-close">×</button></div><div class="music-widget-track"><div class="music-widget-cover">♫</div><div><strong id="mw-title">Nothing playing</strong><small id="mw-artist">Open Nova Music to start</small></div></div><div class="music-widget-controls"><button data-act="prev">‹‹</button><button class="main" data-act="play">▶</button><button data-act="next">››</button></div>';
    el.querySelector('.desktop-widget-close').onclick=()=>remove('music');
    const update=()=>{const st=window.NovaMusicEngine?.state?.()||{};el.querySelector('#mw-title').textContent=st.title||'Nothing playing';el.querySelector('#mw-artist').textContent=st.artist||'Open Nova Music to start';el.querySelector('[data-act="play"]').textContent=st.playing?'Ⅱ':'▶';};
    el.querySelector('[data-act="play"]').onclick=()=>{window.NovaMusicEngine?.toggle();setTimeout(update,30)};el.querySelector('[data-act="prev"]').onclick=()=>window.NovaMusicEngine?.prev();el.querySelector('[data-act="next"]').onclick=()=>window.NovaMusicEngine?.next();document.addEventListener('nova-music-change',update);el._cleanup=()=>document.removeEventListener('nova-music-change',update);update();return el}
  function render(){if(Store.getSettings().experimental?.widgets===false){document.querySelectorAll('.desktop-widget').forEach(e=>{e._cleanup?.();e.remove()});return}document.querySelectorAll('.desktop-widget').forEach(e=>{e._cleanup?.();e.remove()});load().forEach(id=>{if(!widgets[id]||!OS.isInstalled(widgets[id].requires))return;const el=id==='clock'?clockWidget():id==='music'?musicWidget():dailyBibleWidget();document.getElementById('desktop').appendChild(el)})}
  function init(){const btn=document.getElementById('widgets-button');if(btn&&!btn.dataset.widgetBound){btn.dataset.widgetBound='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();panel()})}const bored=document.getElementById('bored-button');if(bored&&!bored.dataset.boredBound){bored.dataset.boredBound='1';bored.addEventListener('click',()=>window.NovaRecommendations?.open())}render()}
  return {init,render,panel,remove};
})();
